src/Entity/Rescue.php
<?php

namespace App\Entity;

use App\Repository\RescueRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\Index;

/**
 * @ORM\Entity(repositoryClass=RescueRepository::class)
 * @ORM\Table(indexes={@Index(name="created_at_index", columns={"created_at"})})
 * @ORM\HasLifecycleCallbacks()
 */
class Rescue
{
    use Timestamp;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="datetime")
     */
    private $birthday;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_adopted;

    /**
     * @ORM\OneToMany(targetEntity=Image::class, mappedBy="rescue", cascade={"persist"})
     */
    private $images;

    /**
     * @ORM\ManyToOne(targetEntity=Gender::class, inversedBy="rescues")
     * @ORM\JoinColumn(nullable=false)
     */
    private $gender;

    public function __construct()
    {
        $this->is_adopted = false;
        $this->images = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->name;
    }
    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getBirthday(): ?\DateTimeInterface
    {
        return $this->birthday;
    }

    public function setBirthday(\DateTimeInterface $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getIsAdopted(): ?bool
    {
        return $this->is_adopted;
    }

    public function setIsAdopted(bool $is_adopted): self
    {
        $this->is_adopted = $is_adopted;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setRescue($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getRescue() === $this) {
                $image->setRescue(null);
            }
        }

        return $this;
    }

    public function getGender(): ?Gender
    {
        return $this->gender;
    }

    public function setGender(?Gender $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

}

templates/pages/about.html.twig
{% extends 'base.html.twig' %}

{% block title %} - Qui sommes nous ?{% endblock %}

{% block body %}
<div class="container flex-align">
    about 
</div>
{% endblock %}

templates/pages/adopted.html.twig
{% extends 'base.html.twig' %}

{% block title %} - Adoptés{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        {% for rescue in rescues %}
        <div class="col-lg-4 col-md-6 col-xs-12 py-3">
            <div class="card">
                <div class="img-card-container">
                    <img src="{{asset('uploads/images/' ~ rescue.images[0].image )}}" class="card-img-top img-card"
                        alt="...">
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{rescue.name}}</h5>
                    <p class="card-text">Né.e le {{rescue.birthday|date('d/m/Y')}} - {{rescue.gender|capitalize}}</p>
                    <p class="card-text"></p>
                    <a href="{{path('show_one', {'id' : rescue.id })}}" class="btn btn-primary">Plus de détails</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/pages/adoption.html.twig
{% extends 'base.html.twig' %}

{% block title %} - Demande d'adoption{% endblock %}

{% block body %}
<div class="container">
    <div class="jumbotron text-center">
        <h1 class="display-4">Demande d'adoption</h1>
        <p class="ml-2">Vous pouvez faire une demande d'adoption de 2 façons :</p>
        <hr class="my-4">
        <h4>Par courrier</h4>
        <p class="lead"><a href="{{asset('uploads/files/DEMANDE-DADOPTION-201920-word.docx')}}" download><i
                    class="fa fa-download"></i> Télécharger le formulaire de demande d'adoption</a> <br> et le
            retourner complété et signé à l'adresse suivante :</p>
        <p>
            Hélène Wang <br> 1 les Jourdennes, 33230 COUTRAS
        </p>
        <hr class="my-4">
        <h4>En ligne</h4>
        <div class="text-center">
            <a class="btn btn-primary btn-lg" href="{{ path('ask_for_adoption_form') }}">Je rempli une demande d'adoption en ligne</a>
        </div>
    </div>
</div>
{% endblock %}

templates/pages/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} - Accueil{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="container">
        <div class="row bg-light p-5">
            <div class="text-center">
                <h1>Association Anim'assistance</h1>
                <h2>Pour La Métropole et ses Îles</h2>
                <p>L’association A.M.I est une association de protection animale basée en France métropolitaine effectuant des sauvetages sur l’île de la Réunion.</p>
                <a href="{{path('about_us')}}" class="btn btn-primary">Entrer</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/pages/show.html.twig
{% extends 'base.html.twig' %}

{% block title %} - {{rescue.name}}{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-lg-6 col-md-6 col-xs-12">
            <h1 class="ml-2">{{rescue.name}}</h1>
            <p>{{rescue.description|raw}}</p>
        </div>
        <div class="col-lg-6 col-md-6 col-xs-12">
            <div class="row">
                {% for image in rescue.images %}
                <div class="col-4" style="height: 300px; width:300px;">
                    <img src="{{asset('uploads/images/' ~ image.image ) }}" class="img-fluid" alt="...">
                </div>
                {% endfor %}
                {% if rescue.isAdopted == false %}
                <iframe
                    src="https://www.facebook.com/plugins/share_button.php?href=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&layout=button&size=large&appId=554187724968318&width=93&height=28"
                    width="93" height="28" style="border:none;overflow:hidden" scrolling="no" frameborder="0"
                    allowfullscreen="true"
                    allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/pages/to_adopt.html.twig
{% extends 'base.html.twig' %}

{% block title %} - À l'adoption{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        {% for rescue in rescues %}
        <div class="col-lg-4 col-md-6 col-xs-12 py-3">
            <div class="card">
                <div class="img-card-container">
                    <img src="{{asset('uploads/images/' ~ rescue.images[0].image )}}" class="card-img-top img-card" alt="...">
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{rescue.name}}</h5>
                    <p class="card-text">Né.e le {{rescue.birthday|date('d/m/Y')}} - {{rescue.gender|capitalize}}</p>
                    <p class="card-text"></p>
                    <a href="{{path('show_one', {'id' : rescue.id })}}" class="btn btn-primary">Plus de détails</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}